# -*- coding: utf-8 -*-
"""Structured content for the migraine TENS manuscript (final harmonized version)."""

# Block types:
# ('title', text)
# ('h1', text)
# ('h2', text)
# ('h3', text)
# ('p', text)              -- normal paragraph; may contain **bold** inline spans
# ('table', caption, headers, rows)
# ('numlist', [items])     -- numbered list
# ('bullet', [items])      -- bullet list
# ('hr',)                  -- section separator

BLOCKS = []
B = BLOCKS

B.append(('title', "Comparative Study on the Effect of Transcutaneous Electrical Nerve Stimulation (TENS) of the Supraorbital and Infraorbital Nerves in Improving Clinical Symptoms and Preventing New Attacks in Patients with Migraine: A Single-Blind, Sham-Controlled Randomized Trial"))

B.append(('h2', "Abstract"))
B.append(('p', "**Background and Objective:** Migraine is a highly prevalent neurological disorder and a leading cause of disability worldwide. Non-invasive neuromodulation with transcutaneous electrical nerve stimulation (TENS) is a promising preventive option, but direct randomized comparisons of supraorbital versus infraorbital stimulation remain limited. It is unclear whether targeting a different trigeminal branch offers comparable or superior efficacy to the more commonly studied supraorbital site. This trial directly compared the clinical efficacy of TENS applied over these two anatomically distinct sites."))
B.append(('p', "**Methods:** In this single-blind, three-arm randomized controlled trial reported in accordance with CONSORT guidelines, 105 adults with migraine were assessed for eligibility, of whom 17 were excluded prior to randomization. Eighty-eight participants meeting ICHD-3 diagnostic criteria were randomized 1:1:1 to supraorbital TENS (n = 30), infraorbital TENS (n = 29), or sham TENS (n = 29); 83 completed treatment and follow-up and were analyzed. Active stimulation was delivered bilaterally at 100 Hz, intensity titrated to a strong but tolerable sensory level (~10 mA), for 30 minutes per session, six sessions weekly for four weeks. Sham electrodes were placed over the supraorbital nerves without current delivery. The primary outcome was monthly headache days at 3 months; secondary outcomes included pain intensity (VAS), disability (MIDAS), headache impact (HIT-6), analgesic-use frequency, and need for preventive medication (MPQ-5)."))
B.append(('p', "**Results:** At 3 months, monthly headache days decreased from 14.18 to 6.59 in the supraorbital group (53.5% reduction, p < 0.001) and from 15.13 to 6.16 in the infraorbital group (59.3% reduction, p < 0.001), with no significant change in the sham group (12.32 to 12.94; p = 0.381). Both active groups showed significant improvements across all secondary outcomes and were superior to sham (all p < 0.001). No significant difference was detected between supraorbital and infraorbital stimulation, though the study was not powered for this comparison. Pain intensity decreased by 46.3% and 44.8% in the supraorbital and infraorbital groups, respectively, versus 8.0% with sham. No serious adverse events occurred."))
B.append(('p', "**Conclusion:** Supraorbital and infraorbital TENS are effective non-invasive adjuncts for improving migraine-related outcomes compared with sham stimulation. However, owing to methodological limitations — including underpowering for the between-site comparison, sham-site asymmetry, and incomplete blinding — these findings should be considered preliminary and hypothesis-generating rather than confirmatory. Larger, site-matched, rigorously blinded trials are warranted."))
B.append(('p', "**Keywords:** Migraine; Transcutaneous electrical nerve stimulation; Supraorbital nerve; Infraorbital nerve; Trigeminal neuromodulation; Randomized controlled trial"))
B.append(('p', "**Trial registration:** Ethics approval code []; IRCT registration number []."))

B.append(('h1', "1. Introduction"))
B.append(('p', "Migraine is a prevalent and disabling neurological disorder, ranked as the second leading cause of disability worldwide by the Global Burden of Disease Study (2016), a finding subsequently reaffirmed by the GBD2019 update [1,2]. It is characterized by recurrent unilateral headaches of moderate to severe intensity, typically accompanied by photophobia, phonophobia, nausea, and vomiting, lasting 4\u201372 hours [3]. Current evidence suggests that migraine represents a primary episodic brain disorder involving activation and sensitization of the trigeminovascular pathway, alongside impaired structural and functional connectivity between cranio-cervical afferents, the brainstem, and higher cortical and subcortical networks [4]."))
B.append(('p', "Migraine affects over 20% of the global population at some point in life, with a substantial proportion seeking medical care: headache accounts for 4.4% of general practice visits [5], approximately 5% of hospital consultations [6], and about 20% of neurology outpatient visits [7]. Epidemiological studies indicate that 4.5% of the Western European population experiences headaches on at least 15 days per month [8], and approximately 1% suffer from chronic migraine [9], placing a significant socioeconomic burden on healthcare systems [10]."))
B.append(('p', "Treatment strategies focus on both prophylaxis and acute attack management. Although pharmacological agents are widely used, their benefits are often offset by adverse effects and the risk of medication overuse headache [11]. This has driven growing interest in non-pharmacological therapies, which offer improved tolerability and safety profiles."))
B.append(('p', "Neuromodulation targeting peripheral nerves has emerged as a promising approach to modulate nociceptive signaling and potentially reduce migraine burden [12,13]. Transcutaneous electrical nerve stimulation (TENS), delivering low-voltage pulsed currents across intact skin, is a non-invasive modality designed to stimulate peripheral nerves for pain control [14]. Its analgesic potential, supported by the gate control theory, has prompted investigations into its utility for migraine [15]."))
B.append(('p', "The Cefaly\u00ae device, the first FDA-cleared medical device for migraine prophylaxis, applies transcutaneous stimulation to the supraorbital and supratrochlear nerves [15,16]. Clinical studies have shown that supraorbital nerve stimulation via TENS (tSNS) can reduce migraine frequency, headache days, and analgesic use, with minimal side effects [16\u201322]. A recent non-inferiority randomized trial comparing tSNS with low-dose (25 mg) topiramate found that tSNS failed to demonstrate non-inferiority, showing a significantly lower 50% responder rate than topiramate (20.6% vs. 33.9%) [23]; however, tSNS demonstrated a markedly more favorable safety profile (adverse event rate 4.3% vs. 22.4%), suggesting it may still be a reasonable option for medication-intolerant patients rather than an equally effective first-line alternative. Comparative studies of neurostimulation parameters, such as frequency, suggest that stimulation settings can influence headache burden [24], raising the question of whether the anatomical site of stimulation may similarly affect clinical outcomes."))
B.append(('p', "In contrast, evidence for infraorbital nerve stimulation remains limited and derives mainly from invasive approaches. Available studies involving nerve blocks or implanted stimulators report reductions in attack frequency, pain intensity, and disability scores [25,26]; however, non-invasive transcutaneous stimulation of the infraorbital nerve has not, to our knowledge, been directly compared with the more established supraorbital site in a randomized setting."))
B.append(('p', "Given the demonstrated efficacy and safety of neuromodulation and its potential to target multiple trigeminal nerve branches, a head-to-head comparison of supraorbital and infraorbital nerve stimulation is warranted. This randomized sham-controlled trial aimed to evaluate and compare the effects of TENS applied to the supraorbital and infraorbital nerves on monthly headache days (primary outcome), pain intensity, disability, headache impact, and medication-related outcomes (secondary outcomes)."))

B.append(('h1', "2. Materials and Methods"))

B.append(('h2', "2.1. Study Design"))
B.append(('p', "A single-blind, three-arm randomized controlled trial was conducted between [month/year] 2020 and [month/year] 2024 at the outpatient Physical Medicine and Rehabilitation clinics of Isfahan University of Medical Sciences, Iran. The study is reported in accordance with the CONSORT 2010 statement and the CONSORT extension for non-pharmacological treatments. The study protocol was approved by the institutional ethics committee (approval code: [XXX]) and prospectively registered in the Iranian Registry of Clinical Trials (IRCT: [XXX], registered on [date]). Written informed consent was obtained from all participants, and the study adhered to the principles of the Declaration of Helsinki."))

B.append(('h2', "2.2. Participants"))
B.append(('p', "Eligible participants were adults aged 18\u201365 years with a confirmed diagnosis of migraine with or without aura according to the International Classification of Headache Disorders, 3rd edition (ICHD-3) criteria (codes 1.1, 1.2.1) [3], and a history of \u22652 migraine attacks per month over the preceding three months. A headache day was defined as any calendar day on which the participant experienced headache pain of at least moderate intensity for \u22654 hours (or of any duration if treated with acute medication), consistent with ICHD-3 diagnostic conventions. Monthly headache days were ascertained from a prospective headache diary completed daily throughout the study period. Written informed consent was obtained from all participants."))
B.append(('p', "A total of 105 patients with migraine, all of whom met the clinical and diagnostic inclusion criteria described above, were initially assessed for eligibility. Of these, 17 were excluded prior to randomization because they were unable to commit to the full course of scheduled treatment sessions (six sessions weekly for four weeks), owing to scheduling conflicts with the clinic or unwillingness to consent to the required session frequency. The remaining 88 patients were randomized 1:1:1 to the supraorbital (n = 30), infraorbital (n = 29), and sham (n = 29) groups, as detailed in the CONSORT flow diagram (Figure 1)."))

B.append(('h2', "2.3. Sample Size Calculation"))
B.append(('p', "Sample size was determined assuming a 95% confidence level (Z1 = 1.96) and 80% statistical power (Z2 = 0.84). Response rate estimates were derived from the ONSTIM feasibility study of occipital nerve stimulation, which reported a 3-month responder rate of 39% in the adjustable stimulation group versus 6% in the preset stimulation group [27]."))
B.append(('p', "Using the formula:"))
B.append(('mono', "n = [(Z1+Z2)^2 x (p1(1-p1) + p2(1-p2))] / (p1-p2)^2"))
B.append(('p', "with Z1 = 1.96, Z2 = 0.84, p1 = 0.39, p2 = 0.06:"))
B.append(('mono', "n = [(1.96+0.84)^2 x (0.39x0.61 + 0.06x0.94)] / (0.39-0.06)^2\nn = [7.84 x (0.2379 + 0.0564)] / (0.33)^2\nn = [7.84 x 0.2943] / 0.1089\nn = 2.307 / 0.1089\nn \u2248 21.2"))
B.append(('p', "the minimum requirement was 22 per group; allowing for an anticipated 20% attrition, the target enrollment was set at approximately 28 per group (~84 total). Following recruitment, 88 participants were ultimately randomized (30, 29, and 29 to the supraorbital, infraorbital, and sham groups, respectively; Section 2.2), of whom 83 completed the protocol and were included in the primary analysis (Section 2.7)."))
B.append(('p', "Note: As ONSTIM evaluated implanted occipital nerve stimulation rather than transcutaneous supraorbital nerve stimulation, this estimate should be interpreted as an approximation drawn from the closest available comparator data, given the paucity of two-arm response-rate data specific to non-invasive supraorbital stimulation at the time of protocol design."))

B.append(('h2', "2.4. Randomization and Blinding"))
B.append(('p', "Participants were allocated in a 1:1:1 ratio to the three study arms using a computer-generated randomization sequence, produced with SPSS software (version 20; IBM Corp., Armonk, NY, USA) with random block sizes of 3 and 6. The randomization sequence was generated by an independent statistician who had no involvement in participant recruitment, treatment delivery, or outcome assessment. Allocation was concealed using sequentially numbered, sealed, opaque envelopes, which were opened by the treating physician only after baseline assessment and confirmation of eligibility."))
B.append(('p', "As this was a single-blind trial, participants remained unaware of their allocated intervention throughout the study. Participants in different study arms had no contact with one another during the treatment period, minimizing the risk of unblinding through cross-group comparison of treatment experience. For the sham arm, the device's \u201con\u201d indicator light was illuminated during each session without delivery of electrical current, simulating the sensory experience of receiving active treatment. Session duration, frequency, and scheduling were standardized across all three arms, and sham electrode placement was matched to that of the supraorbital active-treatment arm, to further preserve participant blinding. Because the sham condition did not replicate the infraorbital electrode placement, the infraorbital-versus-sham contrast is not site-matched; this asymmetry is discussed as a limitation in Section 4.8."))

B.append(('h2', "2.5. Exclusion Criteria"))
B.append(('p', "Exclusion criteria comprised: use of prophylactic migraine medication within two weeks prior to enrollment; receipt of preventive interventions (e.g., nerve block, botulinum toxin) within the past year; medication-overuse headache (ICHD-3 code 8.2); concurrent headache disorders; severe psychiatric or systemic illness; pregnancy or lactation; substance abuse; and treatment non-compliance."))

B.append(('h2', "2.6. Outcome Measures"))
B.append(('p', "Outcomes were assessed at baseline, 1 month, and 3 months after the start of the intervention."))
B.append(('p', "**Primary efficacy outcome:** Monthly headache days at 3 months (number of headache days per month, as defined in Section 2.2)."))
B.append(('p', "**Secondary outcomes** (supportive/exploratory; a Bonferroni adjustment was applied as described in Section 2.8):"))
B.append(('bullet', [
    "Pain intensity on a 0\u201310 visual analog scale (VAS)",
    "Migraine-related disability using the Migraine Disability Assessment (MIDAS) [28]",
    "Headache impact using the Headache Impact Test (HIT-6) [29,30]",
    "Frequency of oral analgesic medication use (number of occasions of acute oral analgesic intake per month)",
    "Need for preventive medication assessed with the Migraine Prevention Questionnaire (MPQ-5) [31]",
]))

B.append(('h2', "2.7. Interventions"))
B.append(('p', "Participants were randomly assigned to one of three intervention groups. Participants in each group were kept blinded to the interventions received by the other two groups."))
B.append(('p', "**Supraorbital TENS (Group 1):** Bilateral transcutaneous electrical nerve stimulation (TENS) was applied over the supraorbital foramina or notches using surface electrodes in the outpatient clinic, under therapist supervision. Stimulation was delivered using a two-channel clinical electrotherapy stimulator (NEWDYN 620F, Novin Medical Engineering Co., Iran) operating in constant-voltage (CV) output mode (maximum output 150 mA at 1 k\u03a9 load). The device was set to the continuous (Normal) TENS mode with fixed parameters for all active sessions: frequency of 100 Hz and pulse width of 200 \u00b5s (both within the device's specified TENS ranges of 0.5\u2013200 Hz and 50\u2013250 \u00b5s, respectively), and a session duration of 30 minutes, read from the device's built-in timer (adjustable 0\u201399 minutes). Current intensity was individually and gradually increased by the therapist, as read from the device display, up to the maximum level tolerated by the participant that produced a strong but comfortable paresthesia (approximately 10 mA). Treatment was scheduled as six sessions per week for four consecutive weeks (24 sessions total)."))
B.append(('p', "**Infraorbital TENS (Group 2):** Participants received bilateral TENS over the infraorbital foramina, using the same device, stimulation parameters, treatment schedule, and intensity-titration protocol as Group 1."))
B.append(('p', "**Sham TENS (Group 3):** Surface electrodes were placed bilaterally over the supraorbital nerves, following the same treatment schedule and session duration as Group 1. The channel output was disabled so that no electrical current was delivered to the electrodes throughout the session; however, the device's indicator light remained illuminated for the full 30 minutes, giving participants the impression that the device was active, thereby providing an inert sham intervention."))
B.append(('p', "Throughout the study, all participants continued to receive standard acute migraine treatment as clinically indicated. Treatment adherence was assessed by attendance at scheduled outpatient sessions. Of the 88 randomized participants, 83 completed the full study protocol (all 24 treatment sessions and the 3-month follow-up assessment); the remaining 5 participants discontinued the study protocol before completion\u2014either because they did not complete the full course of 24 treatment sessions or because they did not attend the 3-month follow-up assessment (see Section 2.8 for details of the sensitivity analyses addressing this attrition)."))
B.append(('p', "**Limitations:** A further limitation is that, although the sham device's indicator light remained illuminated throughout each session to simulate active treatment, the complete absence of paresthesia in the sham group\u2014in contrast to the strong but comfortable paresthesia experienced by participants in the two active TENS groups\u2014may have compromised participant blinding."))

B.append(('h2', "2.8. Statistical Analysis"))
B.append(('p', "All statistical analyses were conducted using SPSS software (version 22; IBM Corp., Armonk, NY, USA). The normality of continuous variables was assessed using the Shapiro\u2013Wilk test; parametric tests were used for normally distributed baseline variables, while non-parametric tests were applied to outcome variables that violated normality assumptions. Continuous variables are presented as mean \u00b1 standard deviation (SD). Baseline comparisons among the three groups were performed using one-way analysis of variance (ANOVA) for continuous variables and Pearson's chi-square test for categorical variables."))
B.append(('p', "Longitudinal within-group changes across baseline, 1 month, and 3 months were evaluated using the Friedman test, with Wilcoxon signed-rank post-hoc pairwise comparisons (Bonferroni-adjusted \u03b1) where the omnibus test was significant. Between-group differences at the 3-month follow-up were assessed using the Kruskal\u2013Wallis test, with Dunn's post-hoc pairwise comparisons (Bonferroni-adjusted for three pairwise contrasts, \u03b1 \u2248 0.017)."))
B.append(('p', "Because five secondary endpoints were examined without a pre-specified multiplicity hierarchy, a Bonferroni-adjusted significance threshold of \u03b1 = 0.01 (0.05/5) was applied for secondary outcomes to control the family-wise error rate. All reported secondary p-values remained < 0.001, so the pattern of results is unchanged."))
B.append(('p', "Between-group mean differences at 3 months are accompanied by approximate 95% confidence intervals (CIs) calculated from group means and SDs using Welch's unequal-variance t-test approximation. These CIs are descriptive effect-size indicators presented alongside the non-parametric test results."))
B.append(('p', "**Sensitivity analysis:** To assess the robustness of the primary findings against potential attrition bias, we conducted a sensitivity analysis for the primary outcome (monthly headache days at 3 months) under two worst-case imputation scenarios for the 5 randomized participants who discontinued the study protocol\u2014either because they did not complete the full course of 24 treatment sessions or because they did not attend the 3-month follow-up assessment. In Scenario A, these 5 participants were assumed to have zero improvement (change from baseline = 0) and were added to the sham group to artificially dilute the treatment effect. In Scenario B, a more pessimistic assumption was applied: these participants were assumed to have deteriorated by 2 attacks per month and were added to the sham group. Additionally, to rule out that extreme baseline values drove the effect, we re-ran the primary analysis after excluding participants with a baseline attack frequency >20 per month. These sensitivity analyses used the same non-parametric methods (Kruskal\u2013Wallis and Mann\u2013Whitney U tests) as the primary analysis."))
B.append(('p', "Of 88 randomized participants, 83 completed the full study protocol and were included in the primary (complete-case) analysis; the remaining 5 participants discontinued the study protocol\u2014either due to incomplete treatment sessions or non-attendance at the 3-month follow-up assessment\u2014and were addressed via the sensitivity analyses described above. A two-sided p-value < 0.05 was considered statistically significant for the primary between-group contrast."))

B.append(('h1', "3. Results"))

B.append(('h2', "3.2. Clinical Outcomes Over Time"))

B.append(('h3', "3.2.1. Monthly Headache Days"))
B.append(('p', "For the primary outcome, both active TENS groups showed a significant change in monthly headache days across the three assessment time points (supraorbital: 14.18 \u00b1 3.95 at baseline to 6.59 \u00b1 2.70 at 3 months; infraorbital: 15.13 \u00b1 4.51 to 6.16 \u00b1 2.48; Friedman p < 0.001 for both), whereas the sham group showed no significant change across time points (12.32 \u00b1 4.99 to 12.94 \u00b1 5.01; Friedman p = 0.381) (Table 2; Figure 2)."))
B.append(('table', "Table 2. Changes in monthly headache days (primary outcome) over the study period. Data are mean \u00b1 SD; within-group p-values are from Friedman tests.",
          ["Group", "n", "Baseline", "1 month", "3 months", "p-value"],
          [
              ["Supraorbital", "28", "14.18 \u00b1 3.95", "7.68 \u00b1 2.84", "6.59 \u00b1 2.70", "<0.001"],
              ["Infraorbital", "27", "15.13 \u00b1 4.51", "9.19 \u00b1 4.03", "6.16 \u00b1 2.48", "<0.001"],
              ["Sham", "28", "12.32 \u00b1 4.99", "14.27 \u00b1 4.15", "12.94 \u00b1 5.01", "0.381"],
          ]))

B.append(('h3', "3.2.2. Pain Intensity (VAS)"))
B.append(('p', "Pain severity showed a significant change across time points in the supraorbital (7.30 \u00b1 1.29 to 3.92 \u00b1 0.97) and infraorbital (7.07 \u00b1 1.47 to 3.90 \u00b1 1.33) groups (Friedman p < 0.001 for both), with no significant change in the sham group (7.10 \u00b1 1.11 to 6.53 \u00b1 1.02; p = 0.125) (Table 3)."))
B.append(('table', "Table 3. Pain intensity (VAS) scores at baseline, 1 month, and 3 months. Data are mean \u00b1 SD.",
          ["Group", "n", "Baseline", "1 month", "3 months", "p-value"],
          [
              ["Supraorbital", "28", "7.30 \u00b1 1.29", "4.07 \u00b1 0.76", "3.92 \u00b1 0.97", "<0.001"],
              ["Infraorbital", "27", "7.07 \u00b1 1.47", "5.05 \u00b1 1.24", "3.90 \u00b1 1.33", "<0.001"],
              ["Sham", "28", "7.10 \u00b1 1.11", "6.16 \u00b1 1.44", "6.53 \u00b1 1.02", "0.125"],
          ]))

B.append(('h3', "3.2.3. Disability (MIDAS)"))
B.append(('p', "MIDAS scores showed a significant change across time points in both active groups (supraorbital: 20.02 \u00b1 5.22 to 9.76 \u00b1 3.12; infraorbital: 17.94 \u00b1 6.30 to 10.30 \u00b1 2.07; Friedman p < 0.001 for both), but not in the sham group (19.36 \u00b1 4.05 to 15.96 \u00b1 5.39; p = 0.174) (Table 4)."))
B.append(('table', "Table 4. MIDAS disability scores at baseline, 1 month, and 3 months. Data are mean \u00b1 SD.",
          ["Group", "n", "Baseline", "1 month", "3 months", "p-value"],
          [
              ["Supraorbital", "28", "20.02 \u00b1 5.22", "12.33 \u00b1 3.94", "9.76 \u00b1 3.12", "<0.001"],
              ["Infraorbital", "27", "17.94 \u00b1 6.30", "13.19 \u00b1 4.62", "10.30 \u00b1 2.07", "<0.001"],
              ["Sham", "28", "19.36 \u00b1 4.05", "17.87 \u00b1 5.20", "15.96 \u00b1 5.39", "0.174"],
          ]))

B.append(('h3', "3.2.4. Headache Impact (HIT-6)"))
B.append(('p', "Significant changes in HIT-6 scores were observed across time points in the supraorbital (62.58 \u00b1 4.78 to 49.48 \u00b1 4.84) and infraorbital (64.22 \u00b1 5.93 to 51.40 \u00b1 3.01) groups (Friedman p < 0.001 for both), with no significant change in the sham group (61.11 \u00b1 3.74 to 62.18 \u00b1 4.13; p = 0.364) (Table 5)."))
B.append(('table', "Table 5. HIT-6 scores at baseline, 1 month, and 3 months. Data are mean \u00b1 SD.",
          ["Group", "n", "Baseline", "1 month", "3 months", "p-value"],
          [
              ["Supraorbital", "28", "62.58 \u00b1 4.78", "51.50 \u00b1 3.61", "49.48 \u00b1 4.84", "<0.001"],
              ["Infraorbital", "27", "64.22 \u00b1 5.93", "51.50 \u00b1 5.39", "51.40 \u00b1 3.01", "<0.001"],
              ["Sham", "28", "61.11 \u00b1 3.74", "62.39 \u00b1 4.20", "62.18 \u00b1 4.13", "0.364"],
          ]))

B.append(('h3', "3.2.5. Medication Usage"))
B.append(('p', "Both active TENS groups showed significant reductions in oral analgesic consumption across time points (supraorbital: 14.62 \u00b1 4.35 to 5.02 \u00b1 2.64; infraorbital: 14.72 \u00b1 3.50 to 5.65 \u00b1 2.55; Friedman p < 0.001 for both), with no significant change in the sham group (14.36 \u00b1 4.27 to 12.06 \u00b1 4.25; p = 0.066). The need for preventive medication, assessed using the MPQ-5, also decreased significantly across time points in both active groups (supraorbital: 26.43 \u00b1 6.49 to 16.77 \u00b1 5.08; infraorbital: 26.52 \u00b1 6.23 to 14.87 \u00b1 5.34; Friedman p < 0.001 for both), with no significant change in the sham group (25.42 \u00b1 6.40 to 24.16 \u00b1 4.23; p = 0.507) (Table 6)."))
B.append(('table', "Table 6. Medication-related outcomes before and after intervention. Need for preventive medication was assessed using the MPQ-5. Data are mean \u00b1 SD.",
          ["Variable", "Group", "n", "Baseline", "1 month", "3 months", "p-value"],
          [
              ["Oral analgesic use frequency", "Supraorbital", "28", "14.62 \u00b1 4.35", "6.21 \u00b1 2.59", "5.02 \u00b1 2.64", "<0.001"],
              ["", "Infraorbital", "27", "14.72 \u00b1 3.50", "8.57 \u00b1 3.20", "5.65 \u00b1 2.55", "<0.001"],
              ["", "Sham", "28", "14.36 \u00b1 4.27", "12.72 \u00b1 2.88", "12.06 \u00b1 4.25", "0.066"],
              ["MPQ-5 (preventive need)", "Supraorbital", "28", "26.43 \u00b1 6.49", "16.73 \u00b1 5.74", "16.77 \u00b1 5.08", "<0.001"],
              ["", "Infraorbital", "27", "26.52 \u00b1 6.23", "15.98 \u00b1 4.63", "14.87 \u00b1 5.34", "<0.001"],
              ["", "Sham", "28", "25.42 \u00b1 6.40", "24.17 \u00b1 6.49", "24.16 \u00b1 4.23", "0.507"],
          ]))

B.append(('h2', "3.3. Between-Group Comparisons at Three Months"))
B.append(('p', "Kruskal\u2013Wallis tests revealed significant differences among the three groups across all six clinical outcomes at 3 months, including the primary outcome of monthly headache days (H(2) = 30.22, p = 2.74\u00d710\u207b\u2077), pain intensity (H(2) = 49.08, p = 2.20\u00d710\u207b\u00b9\u00b9), disability (H(2) = 22.95, p = 1.04\u00d710\u207b\u2075), headache impact (H(2) = 51.82, p = 5.58\u00d710\u207b\u00b9\u00b2), analgesic use frequency (H(2) = 41.46, p = 9.94\u00d710\u207b\u00b9\u2070), and preventive medication need (H(2) = 35.57, p = 1.89\u00d710\u207b\u2078)."))
B.append(('p', "Post-hoc pairwise comparisons were performed using Mann\u2013Whitney U tests, with significance evaluated against a Bonferroni-corrected threshold of \u03b1 = 0.05/18 \u2248 0.0028, applied across all 18 pairwise contrasts (3 pairwise comparisons \u00d7 6 outcomes) to control the family-wise error rate at the strictest level considered. Both active TENS groups were significantly superior to sham across all six outcomes (all p \u2264 0.000279, well below the corrected threshold). No statistically significant differences were observed between supraorbital and infraorbital stimulation for any outcome (all p \u2265 0.15, non-significant even at the unadjusted \u03b1 = 0.05 level) (Table 7). These conclusions were robust to the choice of multiplicity-correction method (per-outcome Bonferroni, Holm sequential, or the pooled 18-comparison Bonferroni correction applied here)."))
B.append(('table', "Table 7. Between-group comparisons at 3 months (Supraorbital n=28, Infraorbital n=27, Sham n=28). Overall test: Kruskal\u2013Wallis H statistic (df=2). Pairwise p-values are from Mann\u2013Whitney U tests; significance was evaluated against a Bonferroni-corrected threshold of \u03b1 = 0.0028 (0.05/18, correcting for all 18 pairwise contrasts). Mean differences (MD) with approximate, descriptive 95% CIs were calculated from group means and SDs (Welch's unequal-variance approximation). Negative MD for symptom scores favors the first-named group when lower values indicate improvement. * Significant at the Bonferroni-corrected threshold \u03b1 = 0.0028.",
          ["Variable", "H (df=2)", "KW p", "Supra\u2212Sham MD [95% CI], p", "Infra\u2212Sham MD [95% CI], p", "Supra\u2212Infra MD [95% CI], p"],
          [
              ["Headache days (days/mo.)", "30.221", "2.74\u00d710\u207b\u2077", "-6.35 [-8.46,-4.24], p<0.001*", "-6.78 [-8.86,-4.70], p<0.001*", "0.43 [-0.94,1.80], p=0.608"],
              ["Pain intensity (VAS)", "49.084", "2.20\u00d710\u207b\u00b9\u00b9", "-2.61 [-3.13,-2.09], p<0.001*", "-2.63 [-3.26,-2.00], p<0.001*", "0.02 [-0.60,0.64], p=0.762"],
              ["Disability (MIDAS)", "22.949", "1.04\u00d710\u207b\u2075", "-6.20 [-8.51,-3.89], p<0.001*", "-5.66 [-7.80,-3.52], p<0.001*", "-0.54 [-1.93,0.85], p=0.159"],
              ["Headache impact (HIT-6)", "51.822", "5.58\u00d710\u207b\u00b9\u00b2", "-12.70 [-15.06,-10.34], p<0.001*", "-10.78 [-12.69,-8.87], p<0.001*", "-1.92 [-4.04,0.20], p=0.160"],
              ["Oral analgesic use frequency", "41.458", "9.94\u00d710\u207b\u00b9\u2070", "-7.04 [-8.89,-5.19], p<0.001*", "-6.41 [-8.25,-4.57], p<0.001*", "-0.63 [-2.00,0.74], p=0.152"],
              ["MPQ-5 (preventive need)", "35.567", "1.89\u00d710\u207b\u2078", "-7.39 [-9.84,-4.94], p<0.001*", "-9.29 [-11.84,-6.74], p<0.001*", "1.90 [-0.86,4.66], p=0.222"],
          ]))

B.append(('h2', "3.4. Adverse Events and Tolerability"))
B.append(('p', "In both active intervention groups, the most commonly reported adverse effects were mild, expected stimulation-related sensations at the electrode site, assessed by open-ended clinician inquiry at each treatment session. These categories were not mutually exclusive, as participants could report more than one sensation. Itching at the electrode site was reported by 9/28 (32.1%) participants in the supraorbital group, 8/27 (29.6%) in the infraorbital group, and 3/28 (10.7%) in the sham group; paresthesia/tingling was reported by 12/28 (42.9%) and 11/27 (40.7%) in the supraorbital and infraorbital groups, respectively, but by no participants in the sham group (0/28), consistent with the absence of delivered current in this arm. The lower but non-zero rate of itching in the sham group likely reflects a non-specific skin reaction to the electrode adhesive/gel, common to all three groups, whereas the higher rates in the active groups may additionally reflect a stimulation-related component. All reported sensations in the active groups were transient, did not require treatment discontinuation, and were consistent with the known tolerability profile of TENS, which is generally well tolerated with mild, self-limiting skin-related adverse effects and no serious adverse events reported in large-scale reviews [32]. No serious adverse events were reported in any group. None of the 5 participants who did not complete the full study protocol (Section 2.7) discontinued due to an adverse event. The open-ended capture method is acknowledged as a limitation (Section 4.8), as milder or non-obvious effects may have been under-reported; the complete absence of paresthesia in the sham group, despite a low background rate of itching, is also discussed in relation to blinding integrity (Section 4.8)."))

B.append(('h1', "4. Discussion"))

B.append(('h2', "4.1. Overview of Main Findings"))
B.append(('p', "The present randomized sham-controlled trial was designed to compare the therapeutic effects of TENS applied over two major sensory branches of the trigeminal nerve \u2014 the supraorbital and infraorbital nerves \u2014 in patients with migraine. Both stimulation protocols resulted in significant improvements in the primary outcome (monthly headache days) and in secondary outcomes. At 3 months, both interventions produced comparable clinical benefits relative to sham, with no statistically significant superiority between stimulation sites; because the trial was neither powered nor pre-specified for equivalence or non-inferiority testing, this finding should not be interpreted as proven equivalence, and it should be weighed alongside the site-mismatched sham design described in Section 2.7."))
B.append(('p', "Beyond statistical significance, the magnitude of improvement appears clinically meaningful: reductions of approximately 45\u201350% in pain intensity, together with substantial improvements in MIDAS and HIT-6 scores, suggest that the observed benefits could translate into tangible improvements in daily functioning and quality of life. However, interpretation of the active-versus-sham contrasts must account for the facts that (a) all outcomes were patient-reported, and (b) the fidelity of participant blinding, particularly in the sham arm, may have been imperfect given the complete absence of paresthesia in that group (Section 2.7); this raises the possibility that expectation effects contributed to some portion of the observed effect sizes, alongside a genuine physiological effect."))

B.append(('h2', "4.2. Comparison with Existing Literature"))
B.append(('p', "Our results align with the growing body of evidence supporting neuromodulation as a non-pharmacological intervention for migraine. The TEAM study (enrollment 2018\u20132019), the largest multicenter randomized trial evaluating external trigeminal nerve stimulation (eTNS) for acute migraine treatment, reported 2-hour pain freedom of 25.5% with active stimulation versus 18.3% with sham (p = 0.043), and freedom from the most bothersome symptom of 56.4% versus 42.3% (p = 0.001) [33]. Although TEAM assessed acute rather than preventive outcomes, it supports the broader clinical relevance of trigeminal neuromodulation. A systematic review and meta-analysis of neuromodulation RCTs similarly found that selected techniques, including supraorbital TENS for prevention, can improve migraine-related outcomes with a generally favorable safety profile; however, overall evidence quality remains limited and effect sizes are typically small to moderate [34]."))
B.append(('p', "Our findings are directionally consistent with this literature. We observed a 46.3% reduction in pain intensity (VAS) in the supraorbital group and 44.8% in the infraorbital group at 3 months, compared with only 8.0% in the sham group (between-group p < 0.001 at 3 months). These results are broadly comparable to those of Jiang et al., who reported a \u226550% responder rate of 39.22% with transcutaneous supraorbital neurostimulation alone, similar to flunarizine monotherapy (46.15%; p = 0.90) [35]; the larger relative reductions observed here should be interpreted cautiously given the between-study differences in design and the selection considerations noted above."))

B.append(('h2', "4.3. Site Comparison: Temporal Pattern and Candidate Mechanisms"))
B.append(('p', "The apparent difference in the temporal pattern of response between the two active sites was not formally tested, as the trial's statistical plan specified between-group comparisons only at the 3-month endpoint (Section 2.8); no interaction test or 1-month between-group comparison was pre-specified. Any interpretation of this numerical pattern is therefore hypothesis-generating only and should not be read as evidence of a genuine difference in onset kinetics between stimulation sites. With that caveat, supraorbital stimulation showed a numerically faster initial response (44.2% pain reduction at 1 month, 46.3% at 3 months), while infraorbital stimulation showed a more gradual trajectory (28.6% at 1 month, 44.8% at 3 months), converging to a similar level by 3 months (Supra\u2212infra MD 0.02, 95% CI -0.60 to 0.64)."))
B.append(('p', "If replicated in adequately powered, site-matched trials, one speculative and untested explanation is anatomical: the supraorbital nerve is a superficial terminal branch of the ophthalmic division of the trigeminal nerve, which may allow faster afferent recruitment, whereas the infraorbital nerve (maxillary division) may engage partially distinct afferent pathways before converging on shared trigeminovascular and brainstem circuits [36,37]. We emphasize that this account is offered only as a possible direction for future mechanistic study, not as an explanation supported by the present data. More broadly, proposed mechanisms for TENS analgesia in migraine include gate-control-mediated suppression of nociceptive transmission via large-diameter A\u03b2 afferents [14], engagement of descending inhibitory pathways (periaqueductal gray, rostral ventromedial medulla, anterior cingulate cortex, hypothalamus, thalamus) [4,36,37], and modulation of serotonergic, GABAergic, and CGRP-related signaling [37]. The similar 3-month outcomes across sites are compatible with convergence of trigeminal sensory inputs within the trigeminocervical complex, but this trial did not include imaging or biomarker measures capable of testing any of these mechanisms directly."))

B.append(('h2', "4.4. Disability, Headache Impact, and Medication Use"))
B.append(('p', "Significant improvements were observed in both disability (MIDAS) and headache impact (HIT-6). MIDAS decreased by 51.2% in the supraorbital group and 42.6% in the infraorbital group (both p < 0.001). HIT-6 decreased by approximately 20% in both active groups, moving from the severe-impact range (\u226560) to little or no impact in the supraorbital group (49.48) and to some impact in the infraorbital group (51.40) [29]. A reduction of approximately 5\u20136 points on the HIT-6 is generally considered clinically meaningful for within-person change [38]; both active groups exceeded this threshold (supraorbital: \u221213.1 points; infraorbital: \u221212.8 points)."))
B.append(('p', "Oral analgesic frequency decreased by 65.7% with supraorbital and 61.6% with infraorbital stimulation; MPQ-5 preventive-need scores decreased by 36.5% and 43.9%, respectively. The sham group showed a non-significant 16.0% reduction in analgesic-use frequency (p = 0.066) and no significant change in MPQ-5 (p = 0.507); absolute analgesic use at 3 months nevertheless remained higher in the sham arm than in either active group. These medication-related findings are clinically relevant given that pharmacological migraine management is often limited by adverse effects, medication-overuse headache, and poor adherence [11,39], and are broadly consistent with the concept that peripheral neuromodulation can, in some settings, reduce medication reliance, although pooled evidence on medication-day outcomes for related modalities such as non-invasive vagus nerve stimulation remains mixed [40]."))

B.append(('h2', "4.5. Comparison Between Active Groups"))
B.append(('p', "The descriptive contrasts below (Table 9) were not statistically significant between the two active arms at 3 months, and the trial was not powered to detect between-site differences; they are presented as hypothesis-generating observations for future, adequately powered, site-matched trials, not as evidence of differential efficacy."))
B.append(('table', "Table 9. Descriptive comparison of active treatment groups. None of the between-site differences below were statistically significant at 3 months (all p \u2265 0.15; Table 7); values are presented for hypothesis generation only.",
          ["Parameter", "Supraorbital", "Infraorbital", "Interpretation"],
          [
              ["Headache day frequency reduction", "53.5%", "59.3%", "Numerical trend only"],
              ["Onset of pain relief", "Faster numerically (44.2% at 1 month)", "Slower numerically (28.6% at 1 month)", "Descriptive only \u2014 not statistically tested"],
              ["3-month pain reduction", "46.3%", "44.8%", "Similar numerically; not tested for equivalence"],
              ["MIDAS improvement", "51.2%", "42.6%", "Numerical trend only"],
              ["HIT-6 reduction", "20.9% (\u221213.1 pts)", "20.0% (\u221212.8 pts)", "Similar numerically; not tested for equivalence"],
              ["Oral analgesic use frequency reduction", "65.7%", "61.6%", "Numerical trend only"],
              ["MPQ-5 preventive-need reduction", "36.5%", "43.9%", "Numerical trend only"],
          ]))

B.append(('h2', "4.6. Clinical Implications"))
B.append(('p', "Because 3-month outcomes were statistically similar between sites, either stimulation site may be clinically acceptable pending confirmatory research; site selection can reasonably consider electrode practicality, tolerability, and patient preference rather than a claimed efficacy advantage. The non-invasive nature, favorable safety profile (Section 3.4), and demonstrated efficacy against sham support TENS as a candidate option within contemporary migraine management pathways; European expert guidance and American Headache Society consensus support neuromodulation for selected patients, particularly those refractory to or intolerant of pharmacological therapies [41,42]. Because the present protocol evaluated repeated preventive sessions with follow-up to 3 months, claims of acute abortive efficacy would require dedicated acute-treatment trial designs. TENS may also be considered as one component of multidisciplinary migraine rehabilitation programs that include lifestyle modification, physiotherapy, exercise therapy, stress management, and psychological interventions [13,41]."))

B.append(('h2', "4.7. Methodological Strengths"))
B.append(('p', "Strengths include a randomized sham-controlled design, participant blinding to the interventions received by the other study arms, matched session procedures across arms for the supraorbital comparison, multidimensional outcomes (VAS, MIDAS, HIT-6, headache days, analgesic use, and MPQ-5), successful baseline demographic balance for age and sex, prospective trial registration and ethics approval obtained prior to patient recruitment, and 3-month follow-up. To the best of our knowledge, this trial is among the first randomized controlled studies to directly compare transcutaneous electrical stimulation of the supraorbital and infraorbital trigeminal branches in migraine."))

B.append(('h2', "4.8. Limitations and Future Directions"))
B.append(('p', "Several limitations should be considered together when interpreting these results:"))
B.append(('numlist', [
    "**Pre-randomization selection and post-randomization attrition:** Of 105 patients screened for eligibility, 17 were excluded before randomization because they were unable to commit to completing the full course of 24 treatment sessions, and 88 were randomized. The randomized sample may therefore be enriched for factors associated with willingness and ability to complete the study, which may limit generalizability. Separately, of the 88 randomized participants, 5 (5.7%) did not complete the full study protocol after randomization, either due to incomplete treatment sessions or non-attendance at the 3-month follow-up assessment (Section 2.7). Sensitivity analyses under worst-case imputation scenarios for these 5 participants (Table 8) confirmed that the primary result remained statistically significant and clinically meaningful even under pessimistic assumptions (zero improvement or deterioration), suggesting that the main finding is robust to this modest degree of post-randomization attrition.",
    "**Underpowered between-site comparison:** The achieved sample size provided only ~64% power for the assumed 3-attack difference, making the non-significant supraorbital-versus-infraorbital comparison inconclusive rather than evidence of equivalence.",
    "**Sham-site asymmetry:** The sham condition replicated only the supraorbital placement; the infraorbital-active versus sham contrast is not site-matched.",
    "**Incomplete blinding:** A formal blinding assessment (e.g., asking participants to guess their allocated group at the end of treatment) was not performed; therefore, the success of participant blinding could not be objectively confirmed. Because all outcomes were patient-reported and the sham group experienced a qualitatively different sensory profile from the active groups (absence of paresthesia despite a low background rate of itching; Section 3.4), the possibility of partial unblinding and associated expectation effects cannot be excluded and may have contributed to some portion of the observed effect sizes.",
    "**Multiplicity correction:** A Bonferroni-adjusted significance threshold (\u03b1 = 0.01 for secondary endpoints; Section 2.8) was applied to account for testing of five secondary outcomes; all secondary p-values remained well below this threshold.",
    "Confidence intervals for between-group differences are descriptive (Welch approximation) rather than formally derived from the rank-based tests used for hypothesis testing.",
    "Short follow-up (3 months) does not establish long-term durability.",
    "Adverse events were captured by open-ended inquiry rather than a standardized checklist.",
    "Single-center design and predominantly female sample (75.9%) limit generalizability.",
    "No subgroup analyses by migraine subtype (episodic vs chronic; with vs without aura).",
    "[Ethics approval number: ______; Trial registration (IRCT) number: ______ \u2014 both obtained prospectively prior to patient recruitment; to be inserted prior to submission.]",
    "**Unblinded treatment delivery and outcome collection:** Neither the treating therapist nor the outcome assessor was blinded to group allocation, although these were two different individuals (only participants were blinded to the interventions received by other arms; Section 2.7). Although primary and secondary outcomes were patient-reported (VAS, MIDAS, HIT-6, headache diaries), the lack of assessor blinding introduces a potential source of performance and detection bias that cannot be excluded.",
]))
B.append(('p', "**Future directions:** Future research should include larger, rigorously blinded, site-matched sham-controlled trials with a pre-specified statistical analysis plan; longer follow-up; mechanistic imaging studies; dose-finding designs; and identification of predictors of treatment response."))

B.append(('h1', "5. Conclusions"))
B.append(('p', "In this single-blind, sham-controlled randomized trial in a highly adherent population, preventive TENS applied over either the supraorbital or the infraorbital trigeminal branch produced significant within-group improvements in monthly headache days (primary outcome), pain intensity (VAS), disability (MIDAS), headache impact (HIT-6), oral analgesic use, and MPQ-5 preventive-need scores. At 3 months, both active protocols were superior to sham across these outcomes, whereas sham showed no significant within-group change. No statistically significant difference was detected between the two active sites at 3 months; given the trial's limited power for this comparison and the sham-site asymmetry, this should be read as inconclusive rather than as evidence of equivalence."))
B.append(('p', "Descriptively, supraorbital stimulation was associated with a faster early reduction in pain intensity, whereas infraorbital stimulation showed a more gradual VAS trajectory and a larger relative reduction in MPQ-5 scores. These temporal patterns are hypothesis-generating only and should not be interpreted as evidence of site-specific superiority."))
B.append(('p', "Taken together, TENS targeting either trigeminal branch may be considered a candidate non-pharmacological adjunctive option for migraine prevention in similar clinical settings, in patients able to commit to the intensive session schedule used here. Confirmation in larger, site-matched, more rigorously blinded trials with longer follow-up, a pre-specified analysis plan, and verifiable prospective registration is warranted before stronger practice recommendations can be made."))

B.append(('h2', "Acknowledgments"))
B.append(('p', "The authors thank all patients who participated in this study and the clinical staff of the Physical Medicine and Rehabilitation clinics at Isfahan University of Medical Sciences for their assistance with recruitment and follow-up assessments."))

B.append(('h2', "Ethics approval and consent to participate"))
B.append(('p', "The study protocol was approved by the institutional ethics committee of Isfahan University of Medical Sciences (ethics approval code: []). All participants provided written informed consent. The trial was prospectively registered in the Iranian Registry of Clinical Trials (IRCT registration number: []). The study was conducted in accordance with the Declaration of Helsinki."))

B.append(('h2', "Competing interests"))
B.append(('p', "The authors declare that they have no competing interests."))

B.append(('h2', "Funding"))
B.append(('p', "This research received no specific grant from any funding agency in the public, commercial, or not-for-profit sectors."))

B.append(('h1', "References"))
REFERENCES = [
"GBD 2016 Headache Collaborators. Global, regional, and national burden of migraine and tension-type headache, 1990\u20132016: a systematic analysis for the Global Burden of Disease Study 2016. Lancet Neurol. 2018;17(11):954\u2013976. doi:10.1016/S1474-4422(18)30322-3",
"Steiner TJ, Stovner LJ, Jensen R, Uluduz D, Katsarava Z; Lifting The Burden: the Global Campaign against Headache. Migraine remains second among the world's causes of disability, and first among young women: findings from GBD2019. J Headache Pain. 2020;21(1):137. doi:10.1186/s10194-020-01208-0",
"Headache Classification Committee of the International Headache Society (IHS). The International Classification of Headache Disorders, 3rd edition. Cephalalgia. 2018;38(1):1\u2013211. doi:10.1177/0333102417738202",
"Akerman S, Romero-Reyes M, Holland PR. Current and novel insights into the neurophysiology of migraine and its implications for therapeutics. Pharmacol Ther. 2017;172:151\u2013170. doi:10.1016/j.pharmther.2016.12.005",
"Tepper SJ, Dahl\u00f6f CG, Dowson A, Newman L, Mansbach H, Jones M, Pham B, Webster C, Salonen R. Prevalence and diagnosis of migraine in patients consulting their physician with a complaint of headache: data from the Landmark Study. Headache. 2004;44(9):856\u2013864. doi:10.1111/j.1526-4610.2004.04167.x",
"Weatherall MW. Acute neurology in a twenty-first century district general hospital. J R Coll Physicians Edinb. 2006;36(3):196\u2013200.",
"Stone J, Carson A, Duncan R, Roberts R, Warlow C, Hibberd C, Coleman R, Cull R, Murray G, Pelosi A, Cavanagh J, Matthews K, Goldbeck R, Smyth R, Walker J, Sharpe M. Who is referred to neurology clinics?\u2014the diagnoses made in 3781 new patients. Clin Neurol Neurosurg. 2010;112(9):747\u2013751. doi:10.1016/j.clineuro.2010.05.011",
"Welch KMA, Goadsby PJ. Chronic daily headache: nosology and pathophysiology. Curr Opin Neurol. 2002;15(3):287\u2013295.",
"Natoli JL, Manack A, Dean B, Butler Q, Turkel CC, Stovner L, Lipton RB. Global prevalence of chronic migraine: a systematic review. Cephalalgia. 2010;30(5):599\u2013609. doi:10.1111/j.1468-2982.2009.01941.x",
"Buse D, Manack A, Serrano D, Reed M, Varon S, Turkel C, Lipton R. Headache impact of chronic and episodic migraine: results from the American Migraine Prevalence and Prevention study. Headache. 2012;52(1):3\u201317. doi:10.1111/j.1526-4610.2011.02046.x",
"Kristoffersen ES, Lundqvist C. Medication-overuse headache: epidemiology, diagnosis and treatment. Ther Adv Drug Saf. 2014;5(2):87\u201399. doi:10.1177/2042098614522683",
"Magis D, Jensen R, Schoenen J. Neurostimulation therapies for primary headache disorders: present and future. Curr Opin Neurol. 2012;25(3):269\u2013278. doi:10.1097/WCO.0b013e3283532023",
"Ambrosini A, D'Alessio C, Magis D, Schoenen J. Targeting pericranial nerve branches to treat migraine: current approaches and perspectives. Cephalalgia. 2015;35(14):1308\u20131322. doi:10.1177/0333102415573511",
"Johnson MI, Paley CA, Howe TE, Sluka KA. Transcutaneous electrical nerve stimulation for acute pain. Cochrane Database Syst Rev. 2015;(6):CD006142. doi:10.1002/14651858.CD006142.pub3",
"Tao H, Wang T, Dong X, Guo Q, Xu H, Wan Q. Effectiveness of transcutaneous electrical nerve stimulation for the treatment of migraine: a meta-analysis of randomized controlled trials. J Headache Pain. 2018;19(1):42. doi:10.1186/s10194-018-0868-9",
"Schoenen J, Vandersmissen B, Jeangette S, Herroelen L, Vandenheede M, G\u00e9rard P, Magis D. Migraine prevention with a supraorbital transcutaneous stimulator: a randomized controlled trial. Neurology. 2013;80(8):697\u2013704. doi:10.1212/WNL.0b013e3182825055",
"Magis D, Sava S, d'Elia TS, Baschi R, Schoenen J. Safety and patients' satisfaction of transcutaneous supraorbital neurostimulation (tSNS) with the Cefaly\u00ae device in headache treatment: a survey of 2,313 headache sufferers in the general population. J Headache Pain. 2013;14:95. doi:10.1186/1129-2377-14-95",
"G\u00e9rardy PY, Fabry D, Fumal A, Schoenen J. A pilot study on supra-orbital surface electrotherapy in migraine. Cephalalgia. 2009;29:134.",
"Russo A, Tessitore A, Conte F, Marcuccio L, Giordano A, Tedeschi G. Transcutaneous supraorbital neurostimulation in \u201cde novo\u201d patients with migraine without aura: the first Italian experience. J Headache Pain. 2015;16:69. doi:10.1186/s10194-015-0551-3",
"Vikelis M, Dermitzakis EV, Spingos KC, Vasiliadis GG, Vlachos GS, Kararizou E. Clinical experience with transcutaneous supraorbital nerve stimulation in patients with refractory migraine or with migraine and intolerance to topiramate: a prospective exploratory clinical study. BMC Neurol. 2017;17:97. doi:10.1186/s12883-017-0869-3",
"Birlea M, Penning S, Callahan K, Schoenen J. Efficacy and safety of external trigeminal neurostimulation in the prevention of chronic migraine: an open-label trial. Cephalalgia Rep. 2019;2:1\u201310. doi:10.1177/2515816319856625",
"Tajti J, Szok D, Ny\u00e1ri A, V\u00e9csei L. Therapeutic strategies that act on the peripheral nervous system in primary headache disorders. Expert Rev Neurother. 2019;19(6):509\u2013528.",
"Ye Y, Xie X, Huang H, Zhang H, Yu Y, Qu W. Efficacy and safety of transcutaneous supraorbital nerve stimulation versus topiramate for migraine prevention: a non-inferiority randomized trial. J Headache Pain. 2026;27:143. doi:10.1186/s10194-026-02367-2",
"Liu Y, Dong Z, Wang T, Ao R, Han X, Tang W, Yu S. Migraine prevention using different frequencies of transcutaneous occipital nerve stimulation: a randomized controlled trial. J Pain. 2017;18(8):1006\u20131015. doi:10.1016/j.jpain.2017.03.012",
"Ilhan Alp S, Alp R. Supraorbital and infraorbital nerve blockade in migraine patients: results of 6-month clinical follow-up. Eur Rev Med Pharmacol Sci. 2013;17(13):1778\u20131781.",
"Reed KL, Conidi F, Bulger R, Will K. Combined concordant peripheral neurostimulation for chronic migraine headaches: a retrospective analysis of 188 consecutive patients. Neurology. 2014;82(10 Suppl):S41.001.",
"Saper JR, Dodick DW, Silberstein SD, McCarville S, Sun M, Goadsby PJ; ONSTIM Investigators. Occipital nerve stimulation for the treatment of intractable chronic migraine headache: ONSTIM feasibility study. Cephalalgia. 2011;31(3):271\u2013285. doi:10.1177/0333102410381142",
"Stewart WF, Lipton RB, Kolodner K, Liberman J, Sawyer J. Reliability of the migraine disability assessment score in a population-based sample of headache sufferers. Cephalalgia. 1999;19(2):107\u2013114. doi:10.1046/j.1468-2982.1999.019002107",
"Yang M, Rendas-Baum R, Varon SF, Kosinski M. Validation of the Headache Impact Test (HIT-6\u2122) across episodic and chronic migraine. Cephalalgia. 2011;31(3):357\u2013367. doi:10.1177/0333102410379890",
"Zandifar A, Asgari F, Haghdoost F, Masjedi SS, Manouchehri N, Banihashemi M, et al. Reliability and validity of the Persian HIT-6 questionnaire in migraine and tension-type headache. Pain Pract. 2014;14(5):e161\u2013e166. doi:10.1111/papr.12163",
"Lipton RB, Serrano D, Buse D, Bigal M, Rupnow M, Biondi D. The Migraine Prevention Questionnaire (MPQ-5): development, psychometric testing and validation. Headache. 2007;47(5):770\u2013771.",
"Johnson MI, Paley CA, Jones G, Mulvey MR, Wittkopf PG. Efficacy and safety of transcutaneous electrical nerve stimulation (TENS) for acute and chronic pain in adults: a systematic review and meta-analysis of 381 studies (the meta-TENS study). BMJ Open. 2022;12(2):e051073. doi:10.1136/bmjopen-2021-051073",
"Kuruvilla DE, Mann JI, Tepper SJ, Starling AJ, Panza J, Johnson MA, Mullin C, et al. Phase 3 randomized, double-blind, sham-controlled Trial of e-TNS for the Acute treatment of Migraine (TEAM). Sci Rep. 2022;12:5110. doi:10.1038/s41598-022-09071-6",
"Moisset X, Pereira B, Ciampi de Andrade D, Fontaine D, Lant\u00e9ri-Minet M, Mawet J. Neuromodulation techniques for acute and preventive migraine treatment: a systematic review and meta-analysis of randomized controlled trials. J Headache Pain. 2020;21(1):142. doi:10.1186/s10194-020-01204-4",
"Jiang L, Yuan DL, Li M, Liu C, Liu Q, Zhang Y, Tan G. Combination of flunarizine and transcutaneous supraorbital neurostimulation improves migraine prophylaxis. Acta Neurol Scand. 2019;139(3):276\u2013283. doi:10.1111/ane.13050",
"Goadsby PJ, Holland PR, Martins-Oliveira M, Hoffmann J, Schankin C, Akerman S. Pathophysiology of migraine: a disorder of sensory processing. Physiol Rev. 2017;97(2):553\u2013622. doi:10.1152/physrev.00034.2015",
"Powell K, Lin K, Tambo W, Saavedra AP, Sciubba D, Al Abed Y, Li C. Trigeminal nerve stimulation: a current state-of-the-art review. Bioelectron Med. 2023;9(1):30. doi:10.1186/s42234-023-00128-z",
"Smelt AFH, Assendelft WJJ, Terwee CB, Ferrari MD, Blom JW. What is a clinically relevant change on the HIT-6 questionnaire? An estimation in a primary-care population of migraine patients. Cephalalgia. 2014;34(1):29\u201336. doi:10.1177/0333102413497599",
"Diener HC, Holle D, Solbach K, Gaul C. Medication-overuse headache: risk factors, pathophysiology and management. Nat Rev Neurol. 2016;12(10):575\u2013583. doi:10.1038/nrneurol.2016.124",
"Song D, Li P, Wang Y, Cao J. Noninvasive vagus nerve stimulation for migraine: a systematic review and meta-analysis of randomized controlled trials. Front Neurol. 2023;14:1190062. doi:10.3389/fneur.2023.1190062",
"Martelletti P, Jensen RH, Antal A, Arcioni R, Brighina F, de Tommaso M, Franzini A, Fontaine D, Heiland M, J\u00fcrgens TP, Leone M, Magis D, Paemeleire K, Palmisani S, Paulus W, May A. Neuromodulation of chronic headaches: position statement from the European Headache Federation. J Headache Pain. 2013;14:86. doi:10.1186/1129-2377-14-86",
"Ailani J, Burch RC, Robbins MS; Board of Directors of the American Headache Society. The American Headache Society Consensus Statement: Update on integrating new migraine treatments into clinical practice. Headache. 2021;61(7):1021\u20131039. doi:10.1111/head.14153",
]
B.append(('reflist', REFERENCES))
